# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='project_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_made', to='project_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='commenttomessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_message', to='project_app.Messages'),
        ),
    ]
