# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191023_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
