# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_party_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='rating',
        ),
    ]
