# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_remove_party_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
