# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20191023_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_message', to='project_app.Party'),
        ),
    ]
